name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        pip install wheel
        pip install bronzebeard
    - name: Build project for each board
      run: |
        bronzebeard -c -i boards/longan_nano/ --include-definitions derzforth.asm
        bronzebeard -c -i boards/wio_lite/ --include-definitions derzforth.asm
        bronzebeard -c -i boards/hifive1_rev_b/ --include-definitions derzforth.asm
